<?php

namespace App\Modules\Stock\Adapters\Saida\Fakes;

class FakeStockSeeder
{
    public static function tabela_produto(): array
    {
        return [
            // ── Bebidas (categoria 1) ──────────────────────────────────────
            [
                'IDPRODUTO' => 1,
                'descricao' => 'Água Mineral 1.5L',
                'categoria' => 1,
                'ps'        => 'P',
                'impostos'  => 2,
                'per'       => round(7 / 100 * 350, 2),   // 24.50
                'qtd'       => 200,
                'validade'  => '2027-06-30',
                'compra'    => 200.00,
                'venda'     => 350.00,
                'barra'     => '6001234500001',
                'obs'       => null,
                'empresa'   => 1,
                'usuario'   => 1,
            ],
            [
                'IDPRODUTO' => 2,
                'descricao' => 'Coca-Cola 350ml',
                'categoria' => 1,
                'ps'        => 'P',
                'impostos'  => 1,
                'per'       => round(14 / 100 * 600, 2),  // 84.00
                'qtd'       => 150,
                'validade'  => '2026-12-31',
                'compra'    => 380.00,
                'venda'     => 600.00,
                'barra'     => '6001234500002',
                'obs'       => null,
                'empresa'   => 1,
                'usuario'   => 1,
            ],
            [
                'IDPRODUTO' => 3,
                'descricao' => 'Sumo de Manga 1L',
                'categoria' => 1,
                'ps'        => 'P',
                'impostos'  => 1,
                'per'       => round(14 / 100 * 750, 2),  // 105.00
                'qtd'       => 80,
                'validade'  => '2026-09-15',
                'compra'    => 450.00,
                'venda'     => 750.00,
                'barra'     => '6001234500003',
                'obs'       => null,
                'empresa'   => 1,
                'usuario'   => 1,
            ],
            [
                'IDPRODUTO' => 4,
                'descricao' => 'Cerveja Cuca 330ml',
                'categoria' => 1,
                'ps'        => 'P',
                'impostos'  => 1,
                'per'       => round(14 / 100 * 500, 2),  // 70.00
                'qtd'       => 300,
                'validade'  => '2026-08-20',
                'compra'    => 300.00,
                'venda'     => 500.00,
                'barra'     => '6001234500004',
                'obs'       => null,
                'empresa'   => 1,
                'usuario'   => 1,
            ],
 
            // ── Alimentação (categoria 2) ──────────────────────────────────
            [
                'IDPRODUTO' => 5,
                'descricao' => 'Arroz Tipo 1 5kg',
                'categoria' => 2,
                'ps'        => 'P',
                'impostos'  => 2,
                'per'       => round(7 / 100 * 2500, 2),  // 175.00
                'qtd'       => 120,
                'validade'  => '2027-01-01',
                'compra'    => 1600.00,
                'venda'     => 2500.00,
                'barra'     => '6001234500005',
                'obs'       => null,
                'empresa'   => 1,
                'usuario'   => 1,
            ],
            [
                'IDPRODUTO' => 6,
                'descricao' => 'Feijão Frade 1kg',
                'categoria' => 2,
                'ps'        => 'P',
                'impostos'  => 2,
                'per'       => round(7 / 100 * 900, 2),   // 63.00
                'qtd'       => 90,
                'validade'  => '2027-03-15',
                'compra'    => 550.00,
                'venda'     => 900.00,
                'barra'     => '6001234500006',
                'obs'       => null,
                'empresa'   => 1,
                'usuario'   => 1,
            ],
            [
                'IDPRODUTO' => 7,
                'descricao' => 'Óleo de Soja 1L',
                'categoria' => 2,
                'ps'        => 'P',
                'impostos'  => 1,
                'per'       => round(14 / 100 * 1200, 2), // 168.00
                'qtd'       => 60,
                'validade'  => '2026-11-30',
                'compra'    => 750.00,
                'venda'     => 1200.00,
                'barra'     => '6001234500007',
                'obs'       => null,
                'empresa'   => 1,
                'usuario'   => 1,
            ],
            [
                'IDPRODUTO' => 8,
                'descricao' => 'Açúcar Refinado 2kg',
                'categoria' => 2,
                'ps'        => 'P',
                'impostos'  => 2,
                'per'       => round(7 / 100 * 1100, 2),  // 77.00
                'qtd'       => 75,
                'validade'  => '2027-05-01',
                'compra'    => 680.00,
                'venda'     => 1100.00,
                'barra'     => '6001234500008',
                'obs'       => null,
                'empresa'   => 1,
                'usuario'   => 1,
            ],
 
            // ── Higiene (categoria 3) ──────────────────────────────────────
            [
                'IDPRODUTO' => 9,
                'descricao' => 'Sabão em Barra 200g',
                'categoria' => 3,
                'ps'        => 'P',
                'impostos'  => 1,
                'per'       => round(14 / 100 * 400, 2),  // 56.00
                'qtd'       => 200,
                'validade'  => '2028-01-01',
                'compra'    => 230.00,
                'venda'     => 400.00,
                'barra'     => '6001234500009',
                'obs'       => null,
                'empresa'   => 1,
                'usuario'   => 1,
            ],
            [
                'IDPRODUTO' => 10,
                'descricao' => 'Pasta Dentífrica 100ml',
                'categoria' => 3,
                'ps'        => 'P',
                'impostos'  => 1,
                'per'       => round(14 / 100 * 850, 2),  // 119.00
                'qtd'       => 110,
                'validade'  => '2027-09-30',
                'compra'    => 500.00,
                'venda'     => 850.00,
                'barra'     => '6001234500010',
                'obs'       => null,
                'empresa'   => 1,
                'usuario'   => 1,
            ],
            [
                'IDPRODUTO' => 11,
                'descricao' => 'Champô Pantene 400ml',
                'categoria' => 3,
                'ps'        => 'P',
                'impostos'  => 1,
                'per'       => round(14 / 100 * 2200, 2), // 308.00
                'qtd'       => 50,
                'validade'  => '2027-12-31',
                'compra'    => 1400.00,
                'venda'     => 2200.00,
                'barra'     => '6001234500011',
                'obs'       => null,
                'empresa'   => 1,
                'usuario'   => 1,
            ],
 
            // ── Electrónica (categoria 4) ──────────────────────────────────
            [
                'IDPRODUTO' => 12,
                'descricao' => 'Pilha AA (par)',
                'categoria' => 4,
                'ps'        => 'P',
                'impostos'  => 1,
                'per'       => round(14 / 100 * 600, 2),  // 84.00
                'qtd'       => 180,
                'validade'  => null,
                'compra'    => 350.00,
                'venda'     => 600.00,
                'barra'     => '6001234500012',
                'obs'       => null,
                'empresa'   => 1,
                'usuario'   => 1,
            ],
            [
                'IDPRODUTO' => 13,
                'descricao' => 'Carregador USB-C 20W',
                'categoria' => 4,
                'ps'        => 'P',
                'impostos'  => 1,
                'per'       => round(14 / 100 * 5500, 2), // 770.00
                'qtd'       => 40,
                'validade'  => null,
                'compra'    => 3200.00,
                'venda'     => 5500.00,
                'barra'     => '6001234500013',
                'obs'       => null,
                'empresa'   => 1,
                'usuario'   => 1,
            ],
            [
                'IDPRODUTO' => 14,
                'descricao' => 'Cabo HDMI 1.5m',
                'categoria' => 4,
                'ps'        => 'P',
                'impostos'  => 1,
                'per'       => round(14 / 100 * 3000, 2), // 420.00
                'qtd'       => 35,
                'validade'  => null,
                'compra'    => 1800.00,
                'venda'     => 3000.00,
                'barra'     => '6001234500014',
                'obs'       => null,
                'empresa'   => 1,
                'usuario'   => 1,
            ],
 
            // ── Papelaria (categoria 5) ────────────────────────────────────
            [
                'IDPRODUTO' => 15,
                'descricao' => 'Caneta Esferográfica Azul',
                'categoria' => 5,
                'ps'        => 'P',
                'impostos'  => 1,
                'per'       => round(14 / 100 * 150, 2),  // 21.00
                'qtd'       => 500,
                'validade'  => null,
                'compra'    => 80.00,
                'venda'     => 150.00,
                'barra'     => '6001234500015',
                'obs'       => null,
                'empresa'   => 1,
                'usuario'   => 1,
            ],
            [
                'IDPRODUTO' => 16,
                'descricao' => 'Resma de Papel A4 500fls',
                'categoria' => 5,
                'ps'        => 'P',
                'impostos'  => 1,
                'per'       => round(14 / 100 * 4500, 2), // 630.00
                'qtd'       => 60,
                'validade'  => null,
                'compra'    => 2800.00,
                'venda'     => 4500.00,
                'barra'     => '6001234500016',
                'obs'       => null,
                'empresa'   => 1,
                'usuario'   => 1,
            ],
            [
                'IDPRODUTO' => 17,
                'descricao' => 'Caderno Espiral 100fls',
                'categoria' => 5,
                'ps'        => 'P',
                'impostos'  => 1,
                'per'       => round(14 / 100 * 900, 2),  // 126.00
                'qtd'       => 150,
                'validade'  => null,
                'compra'    => 550.00,
                'venda'     => 900.00,
                'barra'     => '6001234500017',
                'obs'       => null,
                'empresa'   => 1,
                'usuario'   => 1,
            ],
 
            // ── Serviços (categoria 6) ─────────────────────────────────────
            [
                'IDPRODUTO' => 18,
                'descricao' => 'Instalação de Software',
                'categoria' => 6,
                'ps'        => 'S',
                'impostos'  => 3,
                'per'       => round(6.5 / 100 * 10000, 2), // 650.00
                'qtd'       => 999,
                'validade'  => null,
                'compra'    => 0.00,
                'venda'     => 10000.00,
                'barra'     => '6001234500018',
                'obs'       => 'Serviço de instalação e configuração',
                'empresa'   => 1,
                'usuario'   => 1,
            ],
            [
                'IDPRODUTO' => 19,
                'descricao' => 'Manutenção de Computador',
                'categoria' => 6,
                'ps'        => 'S',
                'impostos'  => 3,
                'per'       => round(6.5 / 100 * 15000, 2), // 975.00
                'qtd'       => 999,
                'validade'  => null,
                'compra'    => 0.00,
                'venda'     => 15000.00,
                'barra'     => '6001234500019',
                'obs'       => 'Diagnóstico e manutenção preventiva',
                'empresa'   => 1,
                'usuario'   => 1,
            ],
            [
                'IDPRODUTO' => 20,
                'descricao' => 'Consultoria por Hora',
                'categoria' => 6,
                'ps'        => 'S',
                'impostos'  => 3,
                'per'       => round(6.5 / 100 * 8000, 2),  // 520.00
                'qtd'       => 999,
                'validade'  => null,
                'compra'    => 0.00,
                'venda'     => 8000.00,
                'barra'     => '6001234500020',
                'obs'       => null,
                'empresa'   => 1,
                'usuario'   => 1,
            ],
 
            // ── Vestuário (categoria 7) ────────────────────────────────────
            [
                'IDPRODUTO' => 21,
                'descricao' => 'Camiseta Básica M',
                'categoria' => 7,
                'ps'        => 'P',
                'impostos'  => 1,
                'per'       => round(14 / 100 * 3500, 2), // 490.00
                'qtd'       => 45,
                'validade'  => null,
                'compra'    => 2000.00,
                'venda'     => 3500.00,
                'barra'     => '6001234500021',
                'obs'       => null,
                'empresa'   => 1,
                'usuario'   => 1,
            ],
            [
                'IDPRODUTO' => 22,
                'descricao' => 'Calça Jeans 38',
                'categoria' => 7,
                'ps'        => 'P',
                'impostos'  => 1,
                'per'       => round(14 / 100 * 12000, 2), // 1680.00
                'qtd'       => 20,
                'validade'  => null,
                'compra'    => 7500.00,
                'venda'     => 12000.00,
                'barra'     => '6001234500022',
                'obs'       => null,
                'empresa'   => 1,
                'usuario'   => 1,
            ],
 
            // ── Limpeza (categoria 8) ──────────────────────────────────────
            [
                'IDPRODUTO' => 23,
                'descricao' => 'Lixívia 1L',
                'categoria' => 8,
                'ps'        => 'P',
                'impostos'  => 1,
                'per'       => round(14 / 100 * 700, 2),  // 98.00
                'qtd'       => 130,
                'validade'  => '2027-04-01',
                'compra'    => 420.00,
                'venda'     => 700.00,
                'barra'     => '6001234500023',
                'obs'       => null,
                'empresa'   => 1,
                'usuario'   => 1,
            ],
            [
                'IDPRODUTO' => 24,
                'descricao' => 'Detergente Líquido 500ml',
                'categoria' => 8,
                'ps'        => 'P',
                'impostos'  => 1,
                'per'       => round(14 / 100 * 900, 2),  // 126.00
                'qtd'       => 100,
                'validade'  => '2027-06-15',
                'compra'    => 550.00,
                'venda'     => 900.00,
                'barra'     => '6001234500024',
                'obs'       => null,
                'empresa'   => 1,
                'usuario'   => 1,
            ],
            [
                'IDPRODUTO' => 25,
                'descricao' => 'Pano de Chão',
                'categoria' => 8,
                'ps'        => 'P',
                'impostos'  => 1,
                'per'       => round(14 / 100 * 1200, 2), // 168.00
                'qtd'       => 70,
                'validade'  => null,
                'compra'    => 700.00,
                'venda'     => 1200.00,
                'barra'     => '6001234500025',
                'obs'       => null,
                'empresa'   => 1,
                'usuario'   => 1,
            ],
 
            // ── Informática (categoria 9) ──────────────────────────────────
            [
                'IDPRODUTO' => 26,
                'descricao' => 'Pendrive 32GB',
                'categoria' => 9,
                'ps'        => 'P',
                'impostos'  => 1,
                'per'       => round(14 / 100 * 4000, 2), // 560.00
                'qtd'       => 55,
                'validade'  => null,
                'compra'    => 2400.00,
                'venda'     => 4000.00,
                'barra'     => '6001234500026',
                'obs'       => null,
                'empresa'   => 1,
                'usuario'   => 1,
            ],
            [
                'IDPRODUTO' => 27,
                'descricao' => 'Mouse USB Óptico',
                'categoria' => 9,
                'ps'        => 'P',
                'impostos'  => 1,
                'per'       => round(14 / 100 * 3500, 2), // 490.00
                'qtd'       => 40,
                'validade'  => null,
                'compra'    => 2000.00,
                'venda'     => 3500.00,
                'barra'     => '6001234500027',
                'obs'       => null,
                'empresa'   => 1,
                'usuario'   => 1,
            ],
            [
                'IDPRODUTO' => 28,
                'descricao' => 'Teclado USB ABNT2',
                'categoria' => 9,
                'ps'        => 'P',
                'impostos'  => 1,
                'per'       => round(14 / 100 * 5000, 2), // 700.00
                'qtd'       => 30,
                'validade'  => null,
                'compra'    => 3000.00,
                'venda'     => 5000.00,
                'barra'     => '6001234500028',
                'obs'       => null,
                'empresa'   => 1,
                'usuario'   => 1,
            ],
            [
                'IDPRODUTO' => 29,
                'descricao' => 'Headset com Microfone',
                'categoria' => 9,
                'ps'        => 'P',
                'impostos'  => 1,
                'per'       => round(14 / 100 * 8500, 2), // 1190.00
                'qtd'       => 25,
                'validade'  => null,
                'compra'    => 5000.00,
                'venda'     => 8500.00,
                'barra'     => '6001234500029',
                'obs'       => null,
                'empresa'   => 1,
                'usuario'   => 1,
            ],
            [
                'IDPRODUTO' => 30,
                'descricao' => 'Webcam HD 720p',
                'categoria' => 9,
                'ps'        => 'P',
                'impostos'  => 1,
                'per'       => round(14 / 100 * 12000, 2), // 1680.00
                'qtd'       => 18,
                'validade'  => null,
                'compra'    => 7200.00,
                'venda'     => 12000.00,
                'barra'     => '6001234500030',
                'obs'       => null,
                'empresa'   => 1,
                'usuario'   => 1,
            ],
 
            // ── Medicina (categoria 10) ────────────────────────────────────
            [
                'IDPRODUTO' => 31,
                'descricao' => 'Paracetamol 500mg cx12',
                'categoria' => 10,
                'ps'        => 'P',
                'impostos'  => 2,
                'per'       => round(7 / 100 * 800, 2),   // 56.00
                'qtd'       => 160,
                'validade'  => '2026-10-31',
                'compra'    => 480.00,
                'venda'     => 800.00,
                'barra'     => '6001234500031',
                'obs'       => 'Analgésico e antipirético',
                'empresa'   => 1,
                'usuario'   => 1,
            ],
            [
                'IDPRODUTO' => 32,
                'descricao' => 'Vitamina C 1000mg cx10',
                'categoria' => 10,
                'ps'        => 'P',
                'impostos'  => 2,
                'per'       => round(7 / 100 * 1500, 2),  // 105.00
                'qtd'       => 90,
                'validade'  => '2027-02-28',
                'compra'    => 900.00,
                'venda'     => 1500.00,
                'barra'     => '6001234500032',
                'obs'       => null,
                'empresa'   => 1,
                'usuario'   => 1,
            ],
            [
                'IDPRODUTO' => 33,
                'descricao' => 'Soro Fisiológico 250ml',
                'categoria' => 10,
                'ps'        => 'P',
                'impostos'  => 2,
                'per'       => round(7 / 100 * 1200, 2),  // 84.00
                'qtd'       => 70,
                'validade'  => '2026-07-15',
                'compra'    => 720.00,
                'venda'     => 1200.00,
                'barra'     => '6001234500033',
                'obs'       => null,
                'empresa'   => 1,
                'usuario'   => 1,
            ],
 
            // ── Produtos adicionais (mix de categorias) ────────────────────
            [
                'IDPRODUTO' => 34,
                'descricao' => 'Leite Condensado 395g',
                'categoria' => 2,
                'ps'        => 'P',
                'impostos'  => 2,
                'per'       => round(7 / 100 * 950, 2),   // 66.50
                'qtd'       => 85,
                'validade'  => '2027-08-01',
                'compra'    => 580.00,
                'venda'     => 950.00,
                'barra'     => '6001234500034',
                'obs'       => null,
                'empresa'   => 1,
                'usuario'   => 1,
            ],
            [
                'IDPRODUTO' => 35,
                'descricao' => 'Fanta Laranja 350ml',
                'categoria' => 1,
                'ps'        => 'P',
                'impostos'  => 1,
                'per'       => round(14 / 100 * 550, 2),  // 77.00
                'qtd'       => 140,
                'validade'  => '2026-12-31',
                'compra'    => 330.00,
                'venda'     => 550.00,
                'barra'     => '6001234500035',
                'obs'       => null,
                'empresa'   => 1,
                'usuario'   => 1,
            ],
            [
                'IDPRODUTO' => 36,
                'descricao' => 'Borracha Branca',
                'categoria' => 5,
                'ps'        => 'P',
                'impostos'  => 1,
                'per'       => round(14 / 100 * 100, 2),  // 14.00
                'qtd'       => 400,
                'validade'  => null,
                'compra'    => 55.00,
                'venda'     => 100.00,
                'barra'     => '6001234500036',
                'obs'       => null,
                'empresa'   => 1,
                'usuario'   => 1,
            ],
            [
                'IDPRODUTO' => 37,
                'descricao' => 'Suporte de Monitor',
                'categoria' => 9,
                'ps'        => 'P',
                'impostos'  => 1,
                'per'       => round(14 / 100 * 9000, 2), // 1260.00
                'qtd'       => 15,
                'validade'  => null,
                'compra'    => 5500.00,
                'venda'     => 9000.00,
                'barra'     => '6001234500037',
                'obs'       => null,
                'empresa'   => 1,
                'usuario'   => 1,
            ],
            [
                'IDPRODUTO' => 38,
                'descricao' => 'Sabonete Líquido 500ml',
                'categoria' => 3,
                'ps'        => 'P',
                'impostos'  => 1,
                'per'       => round(14 / 100 * 1100, 2), // 154.00
                'qtd'       => 95,
                'validade'  => '2027-10-30',
                'compra'    => 670.00,
                'venda'     => 1100.00,
                'barra'     => '6001234500038',
                'obs'       => null,
                'empresa'   => 1,
                'usuario'   => 1,
            ],
            [
                'IDPRODUTO' => 39,
                'descricao' => 'Formação em PHP — 20h',
                'categoria' => 6,
                'ps'        => 'S',
                'impostos'  => 3,
                'per'       => round(6.5 / 100 * 50000, 2), // 3250.00
                'qtd'       => 999,
                'validade'  => null,
                'compra'    => 0.00,
                'venda'     => 50000.00,
                'barra'     => '6001234500039',
                'obs'       => 'Formação presencial ou remota',
                'empresa'   => 1,
                'usuario'   => 1,
            ],
            [
                'IDPRODUTO' => 40,
                'descricao' => 'Álcool em Gel 500ml',
                'categoria' => 3,
                'ps'        => 'P',
                'impostos'  => 1,
                'per'       => round(14 / 100 * 1300, 2), // 182.00
                'qtd'       => 110,
                'validade'  => '2027-03-31',
                'compra'    => 800.00,
                'venda'     => 1300.00,
                'barra'     => '6001234500040',
                'obs'       => null,
                'empresa'   => 1,
                'usuario'   => 1,
            ],
        ];
    }

    public static function tabela_categoria(): array
    {
        return [
            ['ID' => 1,  'categoria' => 'Bebidas',      'empresa' => 1],
            ['ID' => 2,  'categoria' => 'Alimentação',  'empresa' => 1],
            ['ID' => 3,  'categoria' => 'Higiene',      'empresa' => 1],
            ['ID' => 4,  'categoria' => 'Electrónica',  'empresa' => 1],
            ['ID' => 5,  'categoria' => 'Papelaria',    'empresa' => 1],
            ['ID' => 6,  'categoria' => 'Serviços',     'empresa' => 1],
            ['ID' => 7,  'categoria' => 'Vestuário',    'empresa' => 1],
            ['ID' => 8,  'categoria' => 'Limpeza',      'empresa' => 1],
            ['ID' => 9,  'categoria' => 'Informática',  'empresa' => 1],
            ['ID' => 10, 'categoria' => 'Medicina',     'empresa' => 1],
        ];
    }
}
